<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.0.342
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Заявка сайт likedengi74',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'likedengi.ok@yandex.ru',
		'to' => 'likedengi.ok@yandex.ru'
	),
	'fields' => array(
		'custom_U152' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Имя\' не может быть пустым.'
			)
		),
		'custom_U192' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Телефон\' не может быть пустым.'
			)
		),
		'custom_U204' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Желаемая сумма займа',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U216' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Ваш автомобиль',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
